import Provider from "@/components/Provider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider>
      <html lang="en" className="bg-[#1C1C1E] text-white z-0">
        <body>{children}</body>
      </html>
    </Provider>
  );
}
